{
	"openapi": "3.0.0",
	"components": {
		"examples": {},
		"headers": {},
		"parameters": {},
		"requestBodies": {},
		"responses": {},
		"schemas": {
			"ValidateUserErrorJSON": {
				"properties": {
					"message": {
						"type": "string",
						"enum": [
							"Validation failed"
						],
						"nullable": false
					},
					"details": {
						"items": {
							"type": "string"
						},
						"type": "array"
					}
				},
				"required": [
					"message",
					"details"
				],
				"type": "object",
				"additionalProperties": false
			},
			"ValidateErrorJSON": {
				"properties": {
					"message": {
						"type": "string",
						"enum": [
							"Validation failed"
						],
						"nullable": false
					},
					"details": {
						"items": {
							"type": "string"
						},
						"type": "array"
					}
				},
				"required": [
					"message",
					"details"
				],
				"type": "object",
				"additionalProperties": false
			},
			"UserLoginResponseDTO": {
				"description": "Represents a user login response dto object.",
				"properties": {
					"accessToken": {
						"type": "string"
					}
				},
				"required": [
					"accessToken"
				],
				"type": "object",
				"additionalProperties": false
			},
			"ErrorResponse": {
				"properties": {},
				"type": "object",
				"additionalProperties": false
			},
			"UserLoginRequestDTO": {
				"description": "Represents a user login request dto object.",
				"properties": {
					"email": {
						"type": "string",
						"description": "The user's email.",
						"example": "JohnDoe@gmail.com",
						"pattern": "^(.+)@(.+)$"
					},
					"password": {
						"type": "string",
						"description": "The user's password.",
						"example": "SecurePassword123!"
					}
				},
				"required": [
					"email",
					"password"
				],
				"type": "object",
				"additionalProperties": false
			},
			"Pick_UserType.Exclude_keyofUserType.password__": {
				"properties": {
					"email": {
						"type": "string",
						"description": "The user's email.",
						"example": "JohnDoe@gmail.com",
						"pattern": "^(.+)@(.+)$"
					},
					"id": {
						"type": "number",
						"format": "double",
						"description": "The user's identifier.",
						"example": "1"
					},
					"fullname": {
						"type": "string",
						"description": "The user's full name.",
						"example": "John Doe"
					},
					"username": {
						"type": "string",
						"description": "The user's username.",
						"example": "John1Doe"
					},
					"age": {
						"type": "integer",
						"format": "int32",
						"description": "The user's age.",
						"example": 21,
						"minimum": 0
					},
					"createdAt": {
						"type": "string",
						"format": "date-time",
						"description": "The date and time when the user was created.",
						"example": "2024-01-01T12:00:00.000Z"
					},
					"updatedAt": {
						"type": "string",
						"format": "date-time",
						"description": "The date and time when the user was last updated.",
						"example": "2024-01-01T13:00:00.000Z"
					},
					"phone": {
						"type": "string",
						"description": "The user's phone number.",
						"example": "123-456-7890"
					},
					"failedLogins": {
						"type": "number",
						"format": "double",
						"description": "The user's failed login attempts.",
						"example": 0
					},
					"isEnabled": {
						"type": "boolean",
						"description": "The user's account status.",
						"example": true
					}
				},
				"required": [
					"email",
					"id",
					"fullname",
					"username",
					"age",
					"createdAt",
					"updatedAt",
					"phone",
					"failedLogins",
					"isEnabled"
				],
				"type": "object",
				"description": "From T, pick a set of properties whose keys are in the union K"
			},
			"UserRegisterResponseDTO": {
				"description": "Represents a user register response dto object.",
				"properties": {
					"email": {
						"type": "string",
						"description": "The user's email.",
						"example": "JohnDoe@gmail.com",
						"pattern": "^(.+)@(.+)$"
					},
					"id": {
						"type": "number",
						"format": "double",
						"description": "The user's identifier.",
						"example": "1"
					},
					"fullname": {
						"type": "string",
						"description": "The user's full name.",
						"example": "John Doe"
					},
					"username": {
						"type": "string",
						"description": "The user's username.",
						"example": "John1Doe"
					},
					"age": {
						"type": "integer",
						"format": "int32",
						"description": "The user's age.",
						"example": 21,
						"minimum": 0
					},
					"createdAt": {
						"type": "string",
						"format": "date-time",
						"description": "The date and time when the user was created.",
						"example": "2024-01-01T12:00:00.000Z"
					},
					"updatedAt": {
						"type": "string",
						"format": "date-time",
						"description": "The date and time when the user was last updated.",
						"example": "2024-01-01T13:00:00.000Z"
					},
					"phone": {
						"type": "string",
						"description": "The user's phone number.",
						"example": "123-456-7890"
					},
					"failedLogins": {
						"type": "number",
						"format": "double",
						"description": "The user's failed login attempts.",
						"example": 0
					},
					"isEnabled": {
						"type": "boolean",
						"description": "The user's account status.",
						"example": true
					}
				},
				"required": [
					"email",
					"id",
					"fullname",
					"username",
					"age",
					"createdAt",
					"updatedAt",
					"phone",
					"failedLogins",
					"isEnabled"
				],
				"type": "object",
				"additionalProperties": false
			},
			"UserRegisterRequestDTO": {
				"description": "Represents a user object creation request.",
				"properties": {
					"email": {
						"type": "string",
						"description": "The user's email.",
						"example": "JohnDoe@gmail.com",
						"pattern": "^(.+)@(.+)$"
					},
					"password": {
						"type": "string",
						"description": "The user's password.",
						"example": "SecurePassword123!"
					},
					"fullname": {
						"type": "string",
						"description": "The user's full name.",
						"example": "John Doe"
					},
					"username": {
						"type": "string",
						"description": "The user's username.",
						"example": "John1Doe"
					},
					"age": {
						"type": "integer",
						"format": "int32",
						"description": "The user's age.",
						"example": 21,
						"minimum": 0
					},
					"phone": {
						"type": "string",
						"description": "The user's phone number.",
						"example": "123-456-7890"
					}
				},
				"required": [
					"email",
					"password",
					"fullname",
					"username",
					"age",
					"phone"
				],
				"type": "object",
				"additionalProperties": false
			}
		},
		"securitySchemes": {
			"jwt": {
				"type": "http",
				"scheme": "bearer",
				"bearerFormat": "JWT",
				"description": "Enter your bearer token in the format \"Bearer {token}\"",
				"scopes": {
					"ADMIN": "Admin privileges",
					"USER": "User privileges"
				}
			}
		}
	},
	"info": {
		"title": "User Management API",
		"version": "1.0.7",
		"description": "This is a sample server User server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).",
		"termsOfService": "http://swagger.io/terms/",
		"license": {
			"name": {
				"name": "MIT License",
				"url": "opensource.org"
			}
		},
		"contact": {
			"name": "Joseph Adogeri",
			"email": "johndoe@gmail.com",
			"url": "http://example.com"
		}
	},
	"paths": {
		"/users/current": {
			"get": {
				"operationId": "CurrentUser",
				"responses": {
					"201": {
						"description": "Created",
						"content": {
							"application/json": {
								"schema": {},
								"examples": {
									"Example 1": {
										"value": {
											"id": 1,
											"username": "john1doe",
											"fullname": "John Doe",
											"email": "johndoe@tsoa.com",
											"phone": "123-456-7890",
											"age": 21,
											"createdAt": "2023-01-01T10:00:00.000Z",
											"updatedAt": "2023-01-01T11:30:00.000Z",
											"failedLogins": 0,
											"isEnabled": false
										}
									}
								}
							}
						}
					},
					"422": {
						"description": "Validation Failed",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ValidateUserErrorJSON"
								}
							}
						}
					}
				},
				"description": "Creates a new user in the system.",
				"summary": "Create a new user",
				"tags": [
					"User"
				],
				"security": [
					{
						"jwt": []
					}
				],
				"parameters": []
			}
		},
		"/users/login": {
			"post": {
				"operationId": "LoginUser",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {
									"anyOf": [
										{
											"$ref": "#/components/schemas/UserLoginResponseDTO"
										},
										{
											"$ref": "#/components/schemas/ErrorResponse"
										}
									]
								}
							}
						}
					},
					"422": {
						"description": "Validation Failed",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ValidateUserErrorJSON"
								}
							}
						}
					}
				},
				"tags": [
					"User"
				],
				"security": [],
				"parameters": [],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/UserLoginRequestDTO"
							}
						}
					}
				}
			}
		},
		"/users/logout": {
			"post": {
				"operationId": "LogoutUser",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"422": {
						"description": "Validation Failed",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ValidateUserErrorJSON"
								}
							}
						}
					}
				},
				"tags": [
					"User"
				],
				"security": [],
				"parameters": []
			}
		},
		"/users/forgot": {
			"post": {
				"operationId": "ForgotUser",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"422": {
						"description": "Validation Failed",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ValidateUserErrorJSON"
								}
							}
						}
					}
				},
				"tags": [
					"User"
				],
				"security": [],
				"parameters": []
			}
		},
		"/users/reset": {
			"post": {
				"operationId": "ResetUser",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"422": {
						"description": "Validation Failed",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ValidateUserErrorJSON"
								}
							}
						}
					}
				},
				"tags": [
					"User"
				],
				"security": [],
				"parameters": []
			}
		},
		"/users/deactivate": {
			"delete": {
				"operationId": "DeleteUser",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"422": {
						"description": "Validation Failed",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ValidateUserErrorJSON"
								}
							}
						}
					}
				},
				"tags": [
					"User"
				],
				"security": [],
				"parameters": []
			}
		},
		"/users/register": {
			"post": {
				"operationId": "RegisterUser",
				"responses": {
					"201": {
						"description": "Created",
						"content": {
							"application/json": {
								"schema": {
									"anyOf": [
										{
											"$ref": "#/components/schemas/UserRegisterResponseDTO"
										},
										{
											"$ref": "#/components/schemas/ErrorResponse"
										}
									]
								},
								"examples": {
									"Example 1": {
										"value": {
											"id": 1,
											"username": "john1doe",
											"fullname": "John Doe",
											"email": "johndoe@tsoa.com",
											"phone": "123-456-7890",
											"age": 21,
											"createdAt": "2023-01-01T10:00:00.000Z",
											"updatedAt": "2023-01-01T11:30:00.000Z",
											"failedLogins": 0,
											"isEnabled": false
										}
									}
								}
							}
						}
					},
					"422": {
						"description": "Validation Failed",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ValidateUserErrorJSON"
								}
							}
						}
					}
				},
				"description": "Creates a new user in the system.",
				"summary": "Create a new user",
				"tags": [
					"User"
				],
				"security": [],
				"parameters": [],
				"requestBody": {
					"description": "The user details for creation.",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/UserRegisterRequestDTO",
								"description": "The user details for creation."
							}
						}
					}
				}
			}
		},
		"/users/refresh": {
			"post": {
				"operationId": "RefreshToken",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"422": {
						"description": "Validation Failed",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ValidateUserErrorJSON"
								}
							}
						}
					}
				},
				"tags": [
					"User"
				],
				"security": [],
				"parameters": []
			}
		},
		"/users": {
			"get": {
				"operationId": "GetUsers",
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"422": {
						"description": "Validation Failed",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ValidateUserErrorJSON"
								}
							}
						}
					}
				},
				"tags": [
					"User"
				],
				"security": [],
				"parameters": []
			}
		},
		"/auths/current": {
			"get": {
				"operationId": "CurrentUser",
				"responses": {
					"201": {
						"description": "Created",
						"content": {
							"application/json": {
								"schema": {},
								"examples": {
									"Example 1": {
										"value": {
											"id": 1,
											"username": "john1doe",
											"fullname": "John Doe",
											"email": "johndoe@tsoa.com",
											"phone": "123-456-7890",
											"age": 21,
											"createdAt": "2023-01-01T10:00:00.000Z",
											"updatedAt": "2023-01-01T11:30:00.000Z",
											"failedLogins": 0,
											"isEnabled": false
										}
									}
								}
							}
						}
					},
					"422": {
						"description": "Validation Failed",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ValidateErrorJSON"
								}
							}
						}
					}
				},
				"description": "Creates a new user in the system.",
				"summary": "Create a new user",
				"tags": [
					"Auth"
				],
				"security": [
					{
						"jwt": []
					}
				],
				"parameters": []
			}
		},
		"/auths/login": {
			"post": {
				"operationId": "LoginUser",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {
									"anyOf": [
										{
											"$ref": "#/components/schemas/UserLoginResponseDTO"
										},
										{
											"$ref": "#/components/schemas/ErrorResponse"
										}
									]
								}
							}
						}
					},
					"422": {
						"description": "Validation Failed",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ValidateErrorJSON"
								}
							}
						}
					}
				},
				"tags": [
					"Auth"
				],
				"security": [],
				"parameters": [],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/UserLoginRequestDTO"
							}
						}
					}
				}
			}
		},
		"/auths/logout": {
			"post": {
				"operationId": "LogoutUser",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"422": {
						"description": "Validation Failed",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ValidateErrorJSON"
								}
							}
						}
					}
				},
				"tags": [
					"Auth"
				],
				"security": [],
				"parameters": []
			}
		},
		"/auths/forgot": {
			"post": {
				"operationId": "ForgotUser",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"422": {
						"description": "Validation Failed",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ValidateErrorJSON"
								}
							}
						}
					}
				},
				"tags": [
					"Auth"
				],
				"security": [],
				"parameters": []
			}
		},
		"/auths/reset": {
			"post": {
				"operationId": "ResetUser",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"422": {
						"description": "Validation Failed",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ValidateErrorJSON"
								}
							}
						}
					}
				},
				"tags": [
					"Auth"
				],
				"security": [],
				"parameters": []
			}
		},
		"/auths/deactivate": {
			"delete": {
				"operationId": "DeleteUser",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"422": {
						"description": "Validation Failed",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ValidateErrorJSON"
								}
							}
						}
					}
				},
				"tags": [
					"Auth"
				],
				"security": [],
				"parameters": []
			}
		},
		"/auths/register": {
			"post": {
				"operationId": "RegisterUser",
				"responses": {
					"201": {
						"description": "Created",
						"content": {
							"application/json": {
								"schema": {
									"anyOf": [
										{
											"$ref": "#/components/schemas/UserRegisterResponseDTO"
										},
										{
											"$ref": "#/components/schemas/ErrorResponse"
										}
									]
								},
								"examples": {
									"Example 1": {
										"value": {
											"id": 1,
											"username": "john1doe",
											"fullname": "John Doe",
											"email": "johndoe@tsoa.com",
											"phone": "123-456-7890",
											"age": 21,
											"createdAt": "2023-01-01T10:00:00.000Z",
											"updatedAt": "2023-01-01T11:30:00.000Z",
											"failedLogins": 0,
											"isEnabled": false
										}
									}
								}
							}
						}
					},
					"422": {
						"description": "Validation Failed",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ValidateErrorJSON"
								}
							}
						}
					}
				},
				"description": "Creates a new user in the system.",
				"summary": "Create a new user",
				"tags": [
					"Auth"
				],
				"security": [],
				"parameters": [],
				"requestBody": {
					"description": "The user details for creation.",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/UserRegisterRequestDTO",
								"description": "The user details for creation."
							}
						}
					}
				}
			}
		},
		"/auths": {
			"get": {
				"operationId": "GetUsers",
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"422": {
						"description": "Validation Failed",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ValidateErrorJSON"
								}
							}
						}
					}
				},
				"tags": [
					"Auth"
				],
				"security": [],
				"parameters": []
			}
		}
	},
	"servers": [
		{
			"url": "http://localhost:3000",
			"description": "Development server"
		},
		{
			"url": "http://localhost:3000/api/v1",
			"description": "Test Server"
		},
		{
			"url": "http://prod:8080/api/v1",
			"description": "Production server"
		}
	],
	"tags": [
		{
			"name": "User",
			"description": "Operations related to user management, including creation, retrieval, and updates."
		},
		{
			"name": "Auth",
			"description": "Operations related to authentication, including login, logout, and token management."
		}
	]
}